# --- General Backtest Settings ---
backtest_settings:
  data_source: 'data/test_data/'         # <<< CHANGE: Path to a FOLDER or FILE with historical data
  backtest_mode: 'single'               # 'single' or 'portfolio'
  strategy_file: 'sma_cross_strategy'
  strategy_name: 'SmaCross'
  initial_cash: 100000
  commission_pct: 0.002

# --- Strategy-Specific Parameters ---
strategy_params:
  n1: 15
  n2: 30