# --- General Backtest Settings ---
backtest_settings:
  data_source: './data/test_data/'
  backtest_mode: 'single'
  initial_cash: 100000
  commission_pct: 0.002

# --- Strategies to Run ---
# The hyphen (-) is crucial. It creates a list of items.
strategies:
  # - name: 'SmaCross'
  #   file: 'sma_cross_strategy'
  #   params:
  #     n1: 10
  #     n2: 25

  # - name: 'RsiMomentum'
  #   file: 'rsi_momentum_strategy'
  #   params:
  #     upper_bound: 70
  #     lower_bound: 30
  #     rsi_period: 14

  # - name: 'BuyAndHold'
  #   file: 'buy_and_hold_strategy'
  #   params: {}

  - name: 'PriceLevelStrategy'
    file: 'weekly_strategy'
    params:
      lookback_period: 7